#!/usr/bin/env bash
# Run before each Claude Code session: bash scripts/update_claude_snapshot.sh
# Updates the file snapshot in CLAUDE.md so Claude doesn't waste tokens scanning

set -e

SNAPSHOT_FILE="PROJECT_SNAPSHOT.md"

echo "# PROJECT SNAPSHOT" > "$SNAPSHOT_FILE"
echo "# Auto-generated by scripts/update_claude_snapshot.sh" >> "$SNAPSHOT_FILE"
echo "# Run this before each Claude Code session" >> "$SNAPSHOT_FILE"
echo "# Last updated: $(date '+%Y-%m-%d %H:%M')" >> "$SNAPSHOT_FILE"
echo "" >> "$SNAPSHOT_FILE"

echo "## Existing Python files (backend)" >> "$SNAPSHOT_FILE"
find backend/src -type f -name "*.py" | sort >> "$SNAPSHOT_FILE" 2>/dev/null || echo "(backend not found)" >> "$SNAPSHOT_FILE"

echo "" >> "$SNAPSHOT_FILE"
echo "## Existing Python files (bot)" >> "$SNAPSHOT_FILE"
find bot -type f -name "*.py" 2>/dev/null | sort >> "$SNAPSHOT_FILE" || echo "(not created yet)" >> "$SNAPSHOT_FILE"

echo "" >> "$SNAPSHOT_FILE"
echo "## Existing TypeScript files (frontend)" >> "$SNAPSHOT_FILE"
find frontend/src -type f \( -name "*.ts" -o -name "*.tsx" \) 2>/dev/null | sort >> "$SNAPSHOT_FILE" || echo "(not created yet)" >> "$SNAPSHOT_FILE"

echo "" >> "$SNAPSHOT_FILE"
echo "## Config / infra files" >> "$SNAPSHOT_FILE"
find . -maxdepth 3 -type f \( -name "docker-compose*.yml" -o -name "nginx.conf" \
  -o -name "*.env.example" -o -name "Makefile" -o -name "prometheus.yml" \) \
  2>/dev/null | sort >> "$SNAPSHOT_FILE" || true

echo "" >> "$SNAPSHOT_FILE"
echo "## DO NOT recreate any file listed above." >> "$SNAPSHOT_FILE"
echo "## Read CLAUDE.md for architecture rules, then proceed to NEXT task." >> "$SNAPSHOT_FILE"

echo "[OK] PROJECT_SNAPSHOT.md updated"
echo "[OK] Paste contents of PROJECT_SNAPSHOT.md into your Claude Code session"
