# Run before each Claude Code session: powershell -ExecutionPolicy Bypass -File scripts/update_claude_snapshot.ps1
# Updates the file snapshot in PROJECT_SNAPSHOT.md

$SNAPSHOT_FILE = "PROJECT_SNAPSHOT.md"

"# PROJECT SNAPSHOT" | Out-File -FilePath $SNAPSHOT_FILE -Encoding UTF8
"# Auto-generated by scripts/update_claude_snapshot.ps1" | Out-File -FilePath $SNAPSHOT_FILE -Encoding UTF8 -Append
"# Run this before each Claude Code session" | Out-File -FilePath $SNAPSHOT_FILE -Encoding UTF8 -Append
"# Last updated: $(Get-Date -Format 'yyyy-MM-dd HH:mm')" | Out-File -FilePath $SNAPSHOT_FILE -Encoding UTF8 -Append
"" | Out-File -FilePath $SNAPSHOT_FILE -Encoding UTF8 -Append

"## Existing Python files (backend)" | Out-File -FilePath $SNAPSHOT_FILE -Encoding UTF8 -Append
if (Test-Path "backend/src") {
    Get-ChildItem -Recurse "backend/src" -Filter "*.py" | Select-Object FullName | ForEach-Object { $_.FullName } | Sort-Object | Out-File -FilePath $SNAPSHOT_FILE -Encoding UTF8 -Append
} else {
    "(backend not found)" | Out-File -FilePath $SNAPSHOT_FILE -Encoding UTF8 -Append

}

"" | Out-File -FilePath $SNAPSHOT_FILE -Encoding UTF8 -Append
"## Existing Python files (bot)" | Out-File -FilePath $SNAPSHOT_FILE -Encoding UTF8 -Append
if (Test-Path "bot") {
    $botFiles = Get-ChildItem -Recurse "bot" -Filter "*.py" -ErrorAction SilentlyContinue | Select-Object FullName | ForEach-Object { $_.FullName } | Sort-Object
    if ($botFiles) {
        $botFiles | Out-File -FilePath $SNAPSHOT_FILE -Encoding UTF8 -Append
    } else {
        "(not created yet)" | Out-File -FilePath $SNAPSHOT_FILE -Encoding UTF8 -Append
    }
} else {
    "(not created yet)" | Out-File -FilePath $SNAPSHOT_FILE -Encoding UTF8 -Append
}

"" | Out-File -FilePath $SNAPSHOT_FILE -Encoding UTF8 -Append
"## Existing TypeScript files (frontend)" | Out-File -FilePath $SNAPSHOT_FILE -Encoding UTF8 -Append
if (Test-Path "frontend/src") {
    $tsFiles = Get-ChildItem -Recurse "frontend/src" -Include "*.ts","*.tsx" -ErrorAction SilentlyContinue | Select-Object FullName | ForEach-Object { $_.FullName } | Sort-Object
    if ($tsFiles) {
        $tsFiles | Out-File -FilePath $SNAPSHOT_FILE -Encoding UTF8 -Append
    } else {
        "(not created yet)" | Out-File -FilePath $SNAPSHOT_FILE -Encoding UTF8 -Append
    }
} else {
    "(not created yet)" | Out-File -FilePath $SNAPSHOT_FILE -Encoding UTF8 -Append
}

"" | Out-File -FilePath $SNAPSHOT_FILE -Encoding UTF8 -Append
"## Config / infra files" | Out-File -FilePath $SNAPSHOT_FILE -Encoding UTF8 -Append
$configFiles = Get-ChildItem -Recurse -Include "docker-compose*.yml","nginx.conf","*.env.example","Makefile","prometheus.yml" -ErrorAction SilentlyContinue | Where-Object { $_.FullName.Split('\').Count -le 4 } | Select-Object FullName | ForEach-Object { $_.FullName } | Sort-Object
if ($configFiles) {
    $configFiles | Out-File -FilePath $SNAPSHOT_FILE -Encoding UTF8 -Append
}

"" | Out-File -FilePath $SNAPSHOT_FILE -Encoding UTF8 -Append
"## DO NOT recreate any file listed above." | Out-File -FilePath $SNAPSHOT_FILE -Encoding UTF8 -Append
"## Read CLAUDE.md for architecture rules, then proceed to NEXT task." | Out-File -FilePath $SNAPSHOT_FILE -Encoding UTF8 -Append

Write-Host "[OK] PROJECT_SNAPSHOT.md updated"
Write-Host "[OK] Paste contents of PROJECT_SNAPSHOT.md into your Claude Code session"
